# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Summary' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Summery
  pod 'YYKit'
  pod 'CYLTabBarController'
  pod 'AFNetworking', '~> 3.2.1'
  pod 'SDWebImage', '~> 4.4.1'
  pod 'Masonry'
  pod 'MJExtension', '~> 3.0.15.1' #数据转模型
  pod 'Aspects', '~> 1.4.1'  #AOP编程
  # toast
  pod 'Toast'
  target 'SummaryTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
