# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Summary' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Summery
  pod 'YYKit'
  pod 'CYLTabBarController'
  pod 'AFNetworking', '~> 3.2.1'

  target 'SummaryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SummaryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
